apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: node-deployment
  name: node-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: node-deployment
    spec:
      containers:
      - image: IMAGE_PLACEHOLDER
        name: current-alpine
        resources: {}
status: {}
